---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neoload-sli-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: neoload-sli-service
  replicas: 1
  template:
    metadata:
      labels:
        run: neoload-sli-service
    spec:
      containers:
        - name: neoload-sli-service
          image: hrexed/keptn-neoload-sliprovider:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
          - name: logging-level
            value: DEBUG
          - name: NL_WEB_HOST
            valueFrom:
              secretKeyRef:
                name: neoload-sli
                key: NL_WEB_HOST
          - name: NL_API_HOST
            valueFrom:
              secretKeyRef:
                name: neoload-sli
                key: NL_API_HOST
          - name: NL_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: neoload-sli
                key: NL_API_TOKEN
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: neoload-sli-service
  namespace: keptn
  labels:
    run: neoload-sli-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: neoload-sli-service